services:
  app:
    build: ./
    primary: true
    exposePort: 3000
    environment:
      - name: APP_ENV
        value: 'voyage'
      - name: NODE_ENV
        value: 'production'
      - name: DB_HOST
        value: 127.0.0.1
  database:
    image: postgres:13
    environment:
      - name: POSTGRES_USER
        value: 'voyage'
      - name: POSTGRES_PASSWORD
        value: 'voyage'
      - name: POSTGRES_DB
        value: 'voyage'
